[files]
extend-exclude = [
    "**/go.mod",
    "**/test_ossfs.py",
    "**/thirdparty/**",
    "**/vendor/**",
    "**/*.log",
    "docs/_static",
    "misc/cpplint.py",
    "python/vineyard/contrib/kedro/benchmark/mlops/data/**",
]
ignore-hidden = true
ignore-files = true
ignore-dot = true
ignore-vcs = true
ignore-global = true

[default]
binary = false
check-filename = true
check-file = true
extend-ignore-words-re = [
    "o[A-Za-z0-9]+",
    "s[A-Za-z0-9]+",
]

[default.extend-words]
"Aliyun" = "Aliyun"
"allclose" = "allclose"
"ALLOC" = "ALLOC"
"Alluxio" = "Alluxio"
"apierrors" = "apierrors"
"apiextensions" = "apiextensions"
"apimachinery" = "apimachinery"
"apiv" = "apiv"
"Appender" = "Appender"
"arange" = "arange"
"asio" = "asio"
"astype" = "astype"
"Backoff" = "Backoff"
"bdist" = "bdist"
"bigdata" = "bigdata"
"bitcode" = "bitcode"
"bitwidth" = "bitwidth"
"buildx" = "buildx"
"bulkstore" = "bulkstore"
"bytecode" = "bytecode"
"CAOrgainzation" = "CAOrgainzation"
"chatgpt" = "chatgpt"
"checkpointing" = "checkpointing"
"chrono" = "chrono"
"cindex" = "cindex"
"CLASSNAME" = "CLASSNAME"
"clientref" = "clientref"
"clientset" = "clientset"
"clippy" = "clippy"
"cloudpickle" = "cloudpickle"
"CNCF" = "CNCF"
"codecov" = "codecov"
"codegen" = "codegen"
"codereview" = "codereview"
"composability" = "composability"
"configmap" = "configmap"
"Consolidatable" = "Consolidatable"
"consts" = "consts"
"coreutils" = "coreutils"
"cout" = "cout"
"coveragerc" = "coveragerc"
"cpplint" = "cpplint"
"cpprestsdk" = "cpprestsdk"
"crds" = "crds"
"CUDA" = "CUDA"
"cycleclock" = "cycleclock"
"daemonset" = "daemonset"
"dask" = "dask"
"dataframe" = "dataframe"
"dataframes" = "dataframes"
"datafusion" = "datafusion"
"datalens" = "datalens"
"datasource" = "datasource"
"datatypes" = "datatypes"
"davinci" = "davinci"
"DCPPREST" = "DCPPREST"
"debruijn" = "debruijn"
"dedup" = "dedup"
"defaultscheme" = "defaultscheme"
"Deque" = "Deque"
"deserialization" = "deserialization"
"destaticize" = "destaticize"
"distro" = "distro"
"divein" = "divein"
"dlist" = "dlist"
"dlmalloc" = "dlmalloc"
"dlog" = "dlog"
"doctest" = "doctest"
"dropna" = "dropna"
"dtype" = "dtype"
"DVLOG" = "DVLOG"
"endl" = "endl"
"etcdctl" = "etcdctl"
"etcdserverpb" = "etcdserverpb"
"etcdv" = "etcdv"
"exitfirst" = "exitfirst"
"fastpath" = "fastpath"
"filesystems" = "filesystems"
"flajolet" = "flajolet"
"Flink" = "Flink"
"flyteconsole" = "flyteconsole"
"flytectl" = "flytectl"
"flytesnacks" = "flytesnacks"
"formatcp" = "formatcp"
"fsspec" = "fsspec"
"genieai" = "genieai"
"gensym" = "gensym"
"getset" = "getset"
"getxattr" = "getxattr"
"Giraph" = "Giraph"
"gitbook" = "gitbook"
"globalobject" = "globalobject"
"GLOO" = "GLOO"
"goccy" = "goccy"
"gopath" = "gopath"
"GPTAPI" = "GPTAPI"
"graphlearn" = "graphlearn"
"graphscope" = "graphscope"
"hashable" = "hashable"
"hasher" = "hasher"
"hashers" = "hashers"
"hdfs" = "hdfs"
"Healthz" = "Healthz"
"HOSSEINMOEIN" = "HOSSEINMOEIN"
"htap" = "htap"
"htpasswd" = "htpasswd"
"HUGETLB" = "HUGETLB"
"hyperloglog" = "hyperloglog"
"hyperparameters" = "hyperparameters"
"idxmax" = "idxmax"
"idxmin" = "idxmin"
"impls" = "impls"
"Infof" = "Infof"
"inlines" = "inlines"
"inuse" = "inuse"
"iocontext" = "iocontext"
"ipcserver" = "ipcserver"
"iproduct" = "iproduct"
"irecv" = "irecv"
"isend" = "isend"
"isinstance" = "isinstance"
"issigned" = "issigned"
"iszero" = "iszero"
"itertools" = "itertools"
"izip" = "izip"
"Kaggle" = "Kaggle"
"kedro" = "kedro"
"KEEPALIVE" = "KEEPALIVE"
"kprobe" = "kprobe"
"kretprobe" = "kretprobe"
"kubebuilder" = "kubebuilder"
"kubeconfig" = "kubeconfig"
"kustomization" = "kustomization"
"Kustomize" = "Kustomize"
"lambdafy" = "lambdafy"
"ldbc" = "ldbc"
"leaseid" = "leaseid"
"leasekeepalive" = "leasekeepalive"
"libboost" = "libboost"
"libclang" = "libclang"
"libgrape" = "libgrape"
"libgrpc" = "libgrpc"
"libprotobuf" = "libprotobuf"
"livegraph" = "livegraph"
"localobject" = "localobject"
"localobjects" = "localobjects"
"loglog" = "loglog"
"logr" = "logr"
"lossen" = "lossen"
"makefun" = "makefun"
"malloc" = "malloc"
"mallocinfo" = "mallocinfo"
"manylinux" = "manylinux"
"mathjax" = "mathjax"
"maxdepth" = "maxdepth"
"memmap" = "memmap"
"memoryview" = "memoryview"
"metadatas" = "metadatas"
"metakv" = "metakv"
"metas" = "metas"
"metastore" = "metastore"
"metatree" = "metatree"
"microbatches" = "microbatches"
"mimalloc" = "mimalloc"
"minio" = "minio"
"mmap" = "mmap"
"multierr" = "multierr"
"multispace" = "multispace"
"MVCC" = "MVCC"
"nbytes" = "nbytes"
"NCCL" = "NCCL"
"ND" = "ND"
"ndarray" = "ndarray"
"nfilters" = "nfilters"
"nobuffer" = "nobuffer"
"NODENAME" = "NODENAME"
"noindex" = "noindex"
"nonblocking" = "nonblocking"
"nonminimal" = "nonminimal"
"nonoverlapping" = "nonoverlapping"
"nonspaces" = "nonspaces"
"nopython" = "nopython"
"nproc" = "nproc"
"nslices" = "nslices"
"Numpy" = "Numpy"
"objectfs" = "objectfs"
"ogbn" = "ogbn"
"oneof" = "oneof"
"Oobleck" = "Oobleck"
"OPENAI" = "OPENAI"
"ossfs" = "ossfs"
"PARTITIONER" = "PARTITIONER"
"persuing" = "persuing"
"pflag" = "pflag"
"platlib" = "platlib"
"Pluggable" = "Pluggable"
"pointee" = "pointee"
"popen" = "popen"
"POSIX" = "POSIX"
"pplx" = "pplx"
"Preprocess" = "Preprocess"
"printk" = "printk"
"privkey" = "privkey"
"protobuf" = "protobuf"
"ptrguard" = "ptrguard"
"purelib" = "purelib"
"pyarrow" = "pyarrow"
"pyenv" = "pyenv"
"Pylance" = "Pylance"
"pylint" = "pylint"
"pylintrc" = "pylintrc"
"pyorc" = "pyorc"
"pypa" = "pypa"
"pytest" = "pytest"
"pythonapi" = "pythonapi"
"quickstart" = "quickstart"
"rcfile" = "rcfile"
"rdtsc" = "rdtsc"
"rdzv" = "rdzv"
"readwrite" = "readwrite"
"Readyz" = "Readyz"
"realpath" = "realpath"
"rebalance" = "rebalance"
"Rebalancer" = "Rebalancer"
"rechunk" = "rechunk"
"recordbatch" = "recordbatch"
"recordbatches" = "recordbatches"
"reinit" = "reinit"
"reinterpert" = "reinterpert"
"relu" = "relu"
"replicaset" = "replicaset"
"repr" = "repr"
"Reprable" = "Reprable"
"Retryable" = "Retryable"
"rfind" = "rfind"
"roadmap" = "roadmap"
"rpcserver" = "rpcserver"
"rustdoc" = "rustdoc"
"rustfmt" = "rustfmt"
"scikit" = "scikit"
"sendfd" = "sendfd"
"ser" = "ser"
"serde" = "serde"
"setxattr" = "setxattr"
"sharded" = "sharded"
"sighingnow" = "sighingnow"
"significand" = "significand"
"SIGUSR" = "SIGUSR"
"SIMD" = "SIMD"
"skipna" = "skipna"
"skywalking" = "skywalking"
"SLURM" = "SLURM"
"softwareupdate" = "softwareupdate"
"staticize" = "staticize"
"staticized" = "staticized"
"strategized" = "strategized"
"streamable" = "streamable"
"subdir" = "subdir"
"subhealthy" = "subhealthy"
"Succ" = "Succ"
"thirdparty" = "thirdparty"
"thiserror" = "thiserror"
"Timepoint" = "Timepoint"
"toctree" = "toctree"
"TORCHELASTIC" = "TORCHELASTIC"
"tparam" = "tparam"
"traceback" = "traceback"
"transformative" = "transformative"
"typecheck" = "typecheck"
"typekind" = "typekind"
"UDFs" = "UDFs"
"ujson" = "ujson"
"unittests" = "unittests"
"Unpublish" = "Unpublish"
"unsafecoerce" = "unsafecoerce"
"Unstage" = "Unstage"
"uprobe" = "uprobe"
"uretprobe" = "uretprobe"
"varint" = "varint"
"VCDL" = "VCDL"
"vectorize" = "vectorize"
"vfile" = "vfile"
"vineyardcloudnative" = "vineyardcloudnative"
"vineyardctl" = "vineyardctl"
"VINEYARDD" = "VINEYARDD"
"Wattributes" = "Wattributes"
"WEBSOCKETS" = "WEBSOCKETS"
"whitegrid" = "whitegrid"
"Wrapf" = "Wrapf"
"xattr" = "xattr"
"xmls" = "xmls"
"xxhash" = "xxhash"
"zapcore" = "zapcore"
"zxvf" = "zxvf"