controllerManager:
  kubeRbacProxy:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
        - ALL
    image:
      repository: ghcr.io/v6d-io/v6d/kube-rbac-proxy
      tag: v0.13.0
    resources:
      limits:
        cpu: 300m
        memory: 300Mi
      requests:
        cpu: 300m
        memory: 300Mi
  manager:
    image:
      repository: vineyardcloudnative/vineyard-operator
      tag: latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 500m
        memory: 500Mi
      requests:
        cpu: 500m
        memory: 500Mi
  replicas: 1
kubernetesClusterDomain: cluster.local
metricsService:
  ports:
  - name: https
    port: 8443
    targetPort: https
  type: ClusterIP
webhookService:
  ports:
  - port: 443
    protocol: TCP
    targetPort: 9443
  type: ClusterIP
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetMemoryUtilization: 50
  
  scaleUp:
    pods: 2
    periodSeconds: 15
    stabilizationWindowSeconds: 0
  
  scaleDown:
    percent: 50
    periodSeconds: 60
    stabilizationWindowSeconds: 300
fullnameOverride: vineyard
